### PR TITLE
Bumped http, asto and ppom

### PR DESCRIPTION
**Pull request by olenagerasimova**
Update http, asto and ppom and resolved all the problems.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@olegmoz please review/merge/release

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks

**Comment by olegmoz** [comment]
@Sammers21 could you please trigger release for this adapter?

**Comment by Sammers21** [comment]
@rultor, release tag=`0.5`

**Comment by olegmoz** [comment]
@Sammers21 thanks

**Pull request merged**
