### PR TITLE
Upgrade asto and http dependencies

### LINKED ISSUE #46: Update asto and http versions
The versions are outdated and should be updated

### PR DESCRIPTION
**Pull request by Sammers21**
Closes #46

### CODE REVIEW

**Comment by Sammers21** [comment]
@g4s8, can we merge?

**Comment by Sammers21** [comment]
@g4s8, can you release a new version?

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)[/z](https://www.0crat.com/u/paulodamaso) didn't make CR comments

**Pull request merged**
