### PR TITLE
add GemSlice

### PR DESCRIPTION
**Pull request by Sammers21**
`GemSlice` class has been created.

related to #3

### CODE REVIEW

**Comment by g4s8** [comment]
@Sammers21 there are two possible scenarios for closing the ticket:
 1. Submit multiple pull requests for one issue until it's fixed fully, then close it
 2. Submit PR with `todo` and close ticket after merge

But we can't merge uncompleted feature and close the ticket. So you need to either add a `todo` puzzle with next steps to close #3 or remove `resolves` keyword from PR description.

**Comment by Sammers21** [comment]
@g4s8, done. Review the pull request once again

**Comment by 0crat** [comment]
This pull request [#6](https://github.com/artipie/gem-adapter/issues/6) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f2e3a6cc-e18c-497b-9f65-34ee52ac566a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
