### PR TITLE
Downgrade ppom version since a-central has corrupted jars

### LINKED ISSUE #54: Gem build is failing
Release is failing with this error message: https://github.com/artipie/gem-adapter/issues/52#issuecomment-674041928

### PR DESCRIPTION
**Pull request by Sammers21**
Closes #54

### CODE REVIEW

**Comment by 0crat** [comment]
@Sammers21 this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by Sammers21** [comment]
@g4s8, review the PR, please.

**Comment by g4s8** [comment]
@Sammers21 doesn't upgrade to `0.3.9` ppom solve this issue? It fixed same issues for other repositories

**Comment by Sammers21** [comment]
@g4s8, I guess the `0.3.9` will solve the problem just for now, but who knows what will happen in the future. Corrupted jars might appear again. That is why I would suggest staying on `0.3.3` and guarantee safety from future problems. What do you think @g4s8?

**Comment by Sammers21** [comment]
@g4s8, can you review the PR please one more time?

**Comment by g4s8** [comment]
@Sammers21 `0.9.3` doesn't use central.artipie.com for resolving dependencies, it's trying to resolve dependencies from Maven central firstly, see: https://github.com/artipie/ppom/blob/master/pom.xml#L70 it uses central.artipie.com only as a fallback option. But it contains other important changes such as `0.3.5`

**Comment by Sammers21** [comment]
@g4s8, good. Can we merge the PR, the version is 0.3.9 now.

**Comment by 0crat** [comment]
Job `gh:artipie/gem-adapter#57` is not assigned, can't get performer

**Pull request merged**
