### PR TITLE
Bumped http and ppom

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated `http` to `0.16.2` and `ppom` to `0.4.1`

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, all looks good

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5.1`

**Comment by 0crat** [comment]
Job `gh:artipie/gem-adapter#75` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@yegor256 please touch `.rultor.yaml` to allow us releasing `gem-adapter`

**Comment by olegmoz** [comment]
@yegor256 please help us out with release

**Comment by yegor256** [comment]
@olegmoz done

**Comment by olenagerasimova** [comment]
@yegor256 thanks

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.5.1`

**Pull request merged**
