### PR TITLE
Add me as an arch

### PR DESCRIPTION
**Pull request by Sammers21**
Related to #54

### CODE REVIEW

**Comment by Sammers21** [comment]
Review the PR please.

**Comment by 0crat** [comment]
@Sammers21 this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@Sammers21 the build is failing, please try to update to the latest parent pom `0.3.9`, maybe it can fix this issue

**Comment by Sammers21** [comment]
@g4s8, i've found out a solution for the problem. Downgrading to ppom 0.3.3 works.

> @Sammers21 the build is failing, please try to update to the latest parent pom `0.3.9`, maybe it can fix this issue

**Comment by Sammers21** [comment]
@g4s8, can we merge?

**Pull request merged**
